### ISSUE TITLE
do this work now 

### ISSUE THREAD

**Issue by christendom12** [Frogleim/spotify_bot_streamer#10]
Please I was just on a research line and I bumped into this, I would like to know if this works well now, and I don't even need many streams on my playlist it just a max of 300 if I don't know if that is possible, and it is organic if I don't overdo it for sure

**Comment by Frogleim** [comment]
Do you run my code?

**Comment by christendom12** [comment]
I just stumbled on it today in my research and I would love to know more and if i won't get any issues on my playlist with it.

And also if possible it can influence the playlist follows or it's just for the streams alone.

**Comment by Frogleim** [comment]
it's working code. just read readme and do all steps

**Comment by christendom12** [comment]
Okay, I just finished downloading everything as started.

**Comment by christendom12** [comment]
please do you have a telegram where i can communicate directly to you..please ?
